version: "3"
services:
    risqlac:
        build: .
        container_name: risqlac
        network_mode: host
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./data:/app/data
        develop:
            watch:
                - action: rebuild
                  path: ./
                  target: ./
                  ignore:
                      - node_modules/
                      - data/
